function renderPasskeyStatus(){if(!$('passkeyStatus')||!state)return;$('passkeyStatus').textContent=state.settings?.passkeyEnabled?'Passkey подключён ✓':passkeySupported()?'Passkey не подключён':'Passkey не поддерживается браузером';$('enablePasskey').hidden=Boolean(state.settings?.passkeyEnabled)}
async function ensureSession(){if(!state.settings?.passkeyEnabled)return null;if(sessionToken&&Date.now()<sessionExpiresAt-15000)return sessionToken;const result=await loginPasskey(state.settings.apiUrl);sessionToken=result.sessionToken;sessionExpiresAt=Date.now()+Number(result.expiresIn||900)*1000;return sessionToken}
async function authHeaders(){if(state.settings?.passkeyEnabled){const token=await ensureSession();return {'Authorization':`Bearer ${token}`}}const legacy=state.settings?.apiToken||'';return {'X-Logbook-Token':legacy,'Authorization':`Bearer ${legacy}`}}
async function syncNow(){const url=(state.settings.apiUrl||'').replace(/\/$/,'');if(!url){$('syncMessage').textContent='API URL не задан — данные остаются локально.';return}if(!navigator.onLine){$('syncMessage').textContent='Offline — синхронизация отложена.';return}try{const headers=await authHeaders();let done=new Set(),conflicts=[],rejected=[];if(state.pending.length){const res=await fetch(actionUrl(url,'sync'),{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({deviceId:state.deviceId,mutations:state.pending})});if(res.status===401&&state.settings?.passkeyEnabled){sessionToken=null;sessionExpiresAt=0;return syncNow()}if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();done=new Set(data.results.filter(r=>r.status==='APPLIED').map(r=>r.mutationId));conflicts=data.results.filter(r=>r.status==='CONFLICT');rejected=data.results.filter(r=>r.status==='REJECTED');for(const r of conflicts){const m=state.pending.find(x=>x.mutationId===r.mutationId);if(m&&!state.conflicts.some(c=>c.entityType===m.entityType&&c.entityId===m.entityId))state.conflicts.push({entityType:m.entityType,entityId:m.entityId,server:r.server});}state.pending=state.pending.filter(m=>!done.has(m.mutationId)&&!conflicts.some(r=>r.mutationId===m.mutationId)&&!rejected.some(r=>r.mutationId===m.mutationId));}const snap=await fetch(actionUrl(url,'snapshot'),{headers});if(snap.status===401&&state.settings?.passkeyEnabled){sessionToken=null;sessionExpiresAt=0;return syncNow()}if(!snap.ok)throw new Error(`snapshot HTTP ${snap.status}`);mergeSnapshot(state,await snap.json());await persist();$('syncMessage').textContent=rejected.length?`${done.size} synced; ${rejected.length} rejected: ${rejected.map(r=>r.reason||'server policy').join('; ')}`:state.conflicts.length?`${done.size} synced; ${state.conflicts.length} conflict(s) require manual resolution.`:done.size?`${done.size} synced ✓`:'Cloud checked ✓'}catch(e){$('syncMessage').textContent=`Sync error: ${e.message}`}}
$('syncNow').onclick=syncNow;
$('saveSettings').onclick=async()=>{state.settings.apiUrl=$('apiUrl').value.trim();state.settings.apiToken=$('apiToken').value.trim();await persist();renderPasskeyStatus();$('syncMessage').textContent='Сохранено.'};
$('enablePasskey').onclick=async()=>{try{state.settings.apiUrl=$('apiUrl').value.trim();state.settings.apiToken=$('apiToken').value.trim();if(!state.settings.apiUrl)throw new Error('Сначала укажи API URL');if(!state.settings.apiToken)throw new Error('Введи bootstrap sync token из Lockbox');$('syncMessage').textContent='Подтверди биометрию на устройстве…';await registerPasskey(state.settings.apiUrl,state.settings.apiToken);const login=await loginPasskey(state.settings.apiUrl);sessionToken=login.sessionToken;sessionExpiresAt=Date.now()+Number(login.expiresIn||900)*1000;state.settings.passkeyEnabled=true;state.settings.apiToken='';$('apiToken').value='';await persist();renderPasskeyStatus();$('syncMessage').textContent='Passkey подключён. Долгоживущий sync token удалён с устройства ✓'}catch(e){$('syncMessage').textContent=`Passkey error: ${e.message}`}};
$('reauthPasskey').onclick=async()=>{try{sessionToken=null;sessionExpiresAt=0;await ensureSession();$('syncMessage').textContent='Биометрия подтверждена ✓'}catch(e){$('syncMessage').textContent=`Passkey error: ${e.message}`}};
function safeState(){return {version:state.version,cases:state.cases,followups:state.followups,verificationBatches:state.verificationBatches}}
$('exportEncrypted').onclick=async()=>download(`logbook-vault-${today()}.json`,JSON.stringify(await exportEnvelope(),null,2));$('exportJson').onclick=()=>download(`logbook-pseudonymized-${today()}.json`,JSON.stringify(safeState(),null,2));
$('exportCsv').onclick=()=>{const headers=['caseId','surgeryDate','site','eye','specialty','procedure','diagnosis','role','complexity','caseType','status','intraComplication','postComplication','reintervention','preBcva','preIop','finalBcva','latestIop','mediaAvailable'];const q=v=>`"${String(v??'').replaceAll('"','""')}"`;download(`cases-${today()}.csv`,'\ufeff'+[headers.join(','),...state.cases.filter(c=>!c.archived).map(c=>headers.map(h=>q(c[h])).join(','))].join('\n'),'text/csv;charset=utf-8')};
function report(name){const active=state.cases.filter(c=>!c.archived);const m=computeMetrics(active,state.followups);if(name==='Cataract100'){const cs=lastConsecutiveCataracts(active,100);return `LAST CONSECUTIVE INDEPENDENT CATARACT AUDIT\nN=${cs.length}\nIntra-op complications=${cs.filter(c=>c.intraComplication!=='No').length}\nPost-op complications=${cs.filter(c=>c.postComplication!=='No').length}\n\n`+cs.map(c=>`${c.surgeryDate}\t${c.caseId}\t${c.procedure}\t${c.eye}\t${c.intraComplication}/${c.postComplication}`).join('\n')}if(name==='VR'){const v=vrOutcomes(active,state.followups);return `VITREORETINAL OUTCOMES\nTotal VR cases: ${v.cases}\nRetinal detachment cases: ${v.detachmentCases}\nEvaluable attachment outcome: ${v.evaluable}\nPrimary attached: ${v.primaryAttached}\nFinal attached: ${v.finalAttached}`};return `${name}-STYLE SURGICAL SUMMARY\nPrepared: ${new Date().toISOString()}\nTotal active cases: ${m.total}\nIndependent primary cases: ${m.primaryIndependent}\nComplex/very complex: ${m.complex}\nIntra-op complications: ${m.intraComplications}\nPost-op complications: ${m.postComplications}\nReinterventions: ${m.reinterventions}\nFollow-up completeness: ${m.followupComplete}%\n\nBY SPECIALTY\n${Object.entries(m.bySpecialty).map(([k,v])=>`${k}: ${v}`).join('\n')}\n\nNote: preparation summary; not an official institutional form.`}
$$('.reportBtn').forEach(b=>b.onclick=()=>download(`${b.dataset.report}-${today()}.txt`,report(b.dataset.report),'text/plain;charset=utf-8'));
$('makeVerification').onclick=async()=>{const from=$('verifyFrom').value||'0000-01-01',to=$('verifyTo').value||'9999-12-31';const ids=state.cases.filter(c=>!c.archived&&c.surgeryDate>=from&&c.surgeryDate<=to).map(c=>c.caseId);const batch={batchId:`VB-${Date.now()}`,from,to,caseIds:ids,status:'UNVERIFIED',createdAt:new Date().toISOString()};state.verificationBatches.push(batch);await persist();$('verificationOutput').textContent=`Verification batch ${batch.batchId}\nPeriod: ${from} — ${to}\nCases: ${ids.length}\nStatus: UNVERIFIED\n\n${ids.join('\n')}`};
$('backupReminder').onclick=()=>alert('Рекомендация: encrypted vault backup после каждой рабочей недели + два зашифрованных SSD для медиа в разных физических местах.');
$('wipeLocal').onclick=async()=>{if(confirm('Это удалит локальный encrypted vault. Продолжить только если backup уже сохранён.')){await wipeVault();location.reload()}};
function refreshAll(){renderSync();renderFollowSelect();renderDashboard();renderJournal()}
boot();
