function renderDashboard(){const m=computeMetrics(state.cases,state.followups);const cards=[['Операций',m.total],['Primary independent',m.primaryIndependent],['Complex',m.complex],['Complications',m.intraComplications+m.postComplications],['Follow-up',`${m.followupComplete}%`]];$('stats').innerHTML=cards.map(([l,v])=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`).join('');const max=Math.max(1,...Object.values(m.bySpecialty));$('specialtyStats').innerHTML=Object.entries(m.bySpecialty).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')||'<p class="muted">Пока нет данных.</p>';$('qualityStats').innerHTML=`<p>Intra-op complications: <b>${m.intraComplications}</b></p><p>Post-op complications: <b>${m.postComplications}</b></p><p>Reinterventions: <b>${m.reinterventions}</b></p><p>Research candidates: <b>${m.research}</b></p><p>IP Hold: <b>${m.ipHold}</b></p>`;const recent=state.cases.filter(c=>!c.archived).sort((a,b)=>b.surgeryDate.localeCompare(a.surgeryDate)).slice(0,6);$('recentCases').innerHTML=recent.map(caseRow).join('')||'<p class="muted">Добавь первую операцию.</p>'}
function caseRow(c){const n=state.followups.filter(f=>f.caseId===c.caseId).length;return `<div class="case-row"><div><div class="case-id">${esc(c.caseId)}</div><small class="muted">${esc(c.surgeryDate)} · ${esc(c.eye)}</small></div><div><div class="case-title">${esc(c.procedure)}</div><div class="muted">${esc(c.diagnosis||'')}</div><div class="chips"><span class="chip">${esc(c.specialty)}</span><span class="chip">${esc(c.complexity)}</span><span class="chip ${c.status==='IP_HOLD'?'ip':''}">${esc(c.status)}</span><span class="chip">${n} FU</span></div></div><div><button class="ghost small editCase" data-id="${esc(c.caseId)}">Edit</button> <button class="ghost small archiveCase" data-id="${esc(c.caseId)}">Archive</button></div></div>`}
function renderJournal(){const q=$('search').value.toLowerCase().trim(),sp=$('filterSpecialty').value;const rows=state.cases.filter(c=>!c.archived).filter(c=>(!sp||c.specialty===sp)&&(!q||JSON.stringify(c).toLowerCase().includes(q))).sort((a,b)=>b.surgeryDate.localeCompare(a.surgeryDate));$('caseList').innerHTML=rows.map(caseRow).join('')||'<p class="muted">Ничего не найдено.</p>';$$('.editCase').forEach(b=>b.onclick=()=>editCase(b.dataset.id));$$('.archiveCase').forEach(b=>b.onclick=()=>archiveCase(b.dataset.id))}
$('search').oninput=renderJournal;$('filterSpecialty').onchange=renderJournal;
function editCase(id){const c=state.cases.find(x=>x.caseId===id);if(!c)return;showView('operation');currentEdit=id;for(const [id,key] of [['caseId','caseId'],['surgeryDate','surgeryDate'],['site','site'],['eye','eye'],['specialty','specialty'],['procedure','procedure'],['diagnosis','diagnosis'],['complexity','complexity'],['caseType','caseType'],['role','role'],['status','status'],['preBcva','preBcva'],['finalBcva','finalBcva'],['previousSurgery','previousSurgery'],['riskFactors','riskFactors'],['keyTechnique','keyTechnique'],['intraComplication','intraComplication'],['postComplication','postComplication'],['reintervention','reintervention'],['mediaAvailable','mediaAvailable'],['mediaStorageId','mediaStorageId'],['consentScience','consentScience'],['consentPublic','consentPublic'],['clinicalPearl','clinicalPearl']])if($(id)&&c[key]!=null)$(id).value=c[key];$('preIop').value=c.preIop??'';$('latestIop').value=c.latestIop??'';renderSpecialty(c.specialty);for(const [k,v] of Object.entries(c.specialtyData||{})){const el=$(`sp_${k}`);if(el)el.value=v}}
async function archiveCase(id){if(!confirm(`Архивировать ${id}?`))return;const c=state.cases.find(x=>x.caseId===id);c.archived=true;c.revision++;c.updatedAt=new Date().toISOString();queue('case',id,c,c.revision-1,'ARCHIVE');await persist();renderJournal();renderDashboard()}
function renderSync(){$('netBadge').textContent=navigator.onLine?'online':'offline';$('syncBadge').textContent=`${state?.pending?.length||0} pending`;renderConflicts()}
function renderConflicts(){if(!$('conflictList')||!state)return;const cs=state.conflicts||[];$('conflictList').innerHTML=cs.length?cs.map(c=>`<div class="case-row"><div><div class="case-id">${esc(c.entityId)}</div><small class="muted">${esc(c.entityType)} conflict</small></div><div><div class="case-title">Cloud revision ${esc(c.server?.revision||'?')}</div><div class="muted">Локальная версия не была перезаписана.</div></div><div><button class="ghost small keepLocal" data-type="${esc(c.entityType)}" data-id="${esc(c.entityId)}">Keep local</button> <button class="ghost small useCloud" data-type="${esc(c.entityType)}" data-id="${esc(c.entityId)}">Use cloud</button></div></div>`).join(''):'<p class="muted">Конфликтов нет.</p>';$$('.keepLocal').forEach(b=>b.onclick=async()=>{resolveConflict(state,b.dataset.type,b.dataset.id,'KEEP_LOCAL');await persist();renderConflicts()});$$('.useCloud').forEach(b=>b.onclick=async()=>{resolveConflict(state,b.dataset.type,b.dataset.id,'USE_CLOUD');await persist();refreshAll()})}
window.addEventListener('online',()=>{renderSync();syncNow()});window.addEventListener('offline',renderSync);
function actionUrl(base,action){const u=new URL(base);u.searchParams.set('action',action);return u.toString()}
