let state=null,pin=null,currentEdit=null,sessionToken=null,sessionExpiresAt=0;
const $=id=>document.getElementById(id);const $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function download(name,data,type='application/json'){const b=data instanceof Blob?data:new Blob([data],{type});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function initDefaults(){ $('surgeryDate').value=today();$('fuDate').value=today();$('caseId').value=nextCaseId(new Date().getFullYear(),state.cases.map(c=>c.caseId));$('mediaStorageId').value=$('caseId').value;}
async function persist(){await saveVault(state,pin);renderSync();}
function queue(entityType,entityId,payload,expectedRevision=0,operation='UPSERT',transitionConfirmed=false){state.pending.push({mutationId:crypto.randomUUID(),entityType,entityId,payload,expectedRevision,operation,transitionConfirmed:Boolean(transitionConfirmed),createdAt:new Date().toISOString()})}
async function boot(){const exists=await vaultExists();$('setupBlock').hidden=exists;$('unlockBlock').hidden=!exists;$('unlock').hidden=false}
$('createVault').onclick=async()=>{try{pin=$('newPin').value;state=await createVault(pin);openApp()}catch(e){$('authError').textContent=e.message}};
$('restoreVault').onclick=async()=>{try{const file=$('restoreFile').files?.[0];if(!file)throw new Error('Выбери encrypted backup JSON');pin=$('newPin').value;if(!/^\d{6,}$/.test(pin))throw new Error('Введи PIN этого backup');const env=JSON.parse(await file.text());await importEnvelope(env,pin);state=await loadVault(pin);openApp()}catch(e){$('authError').textContent=`Restore error: ${e.message}`}};
$('unlockBtn').onclick=async()=>{try{pin=$('pin').value;state=await loadVault(pin);openApp()}catch(e){$('authError').textContent='Неверный PIN или повреждённый vault'}};
function openApp(){$('unlock').hidden=true;$('app').hidden=false;state.settings ||= {apiUrl:'',apiToken:'',passkeyEnabled:false};state.pending ||= [];state.followups ||= [];state.verificationBatches ||= [];state.conflicts ||= [];$('apiUrl').value=state.settings.apiUrl||'';$('apiToken').value=state.settings.apiToken||'';renderPasskeyStatus();initDefaults();refreshAll();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
$('lockBtn').onclick=()=>{state=null;pin=null;sessionToken=null;sessionExpiresAt=0;$('app').hidden=true;$('unlock').hidden=false;$('pin').value=''};
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='journal')renderJournal();if(name==='dashboard')renderDashboard();if(name==='followup')renderFollowSelect();}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-go]').forEach(b=>b.onclick=()=>showView(b.dataset.viewGo));
$('regenId').onclick=()=>{ $('caseId').value=nextCaseId(new Date().getFullYear(),state.cases.map(c=>c.caseId));$('mediaStorageId').value=$('caseId').value };
$('specialty').onchange=()=>renderSpecialty($('specialty').value);
function renderSpecialty(sp){const fn=specialtyTemplates[sp];$('specialtyCard').hidden=!fn;$('specialtyFields').innerHTML=fn?fn():'';$('specialtyTitle').textContent=sp?`${sp} module`:'Специальный модуль'}
function caseFromForm(){const specialty=$('specialty').value;const obj={caseId:$('caseId').value.trim(),surgeryDate:$('surgeryDate').value,site:$('site').value.trim(),eye:$('eye').value,specialty,procedure:$('procedure').value.trim(),diagnosis:$('diagnosis').value.trim(),complexity:$('complexity').value,caseType:$('caseType').value,role:$('role').value,status:$('status').value,preBcva:$('preBcva').value,preIop:$('preIop').value?Number($('preIop').value):null,finalBcva:$('finalBcva').value,latestIop:$('latestIop').value?Number($('latestIop').value):null,previousSurgery:$('previousSurgery').value.trim(),riskFactors:$('riskFactors').value.trim(),keyTechnique:$('keyTechnique').value.trim(),intraComplication:$('intraComplication').value,postComplication:$('postComplication').value,reintervention:$('reintervention').value,mediaAvailable:$('mediaAvailable').value,mediaStorageId:$('mediaStorageId').value.trim(),consentScience:$('consentScience').value,consentPublic:$('consentPublic').value,clinicalPearl:$('clinicalPearl').value.trim(),specialtyData:collectSpecialtyData($('specialtyFields'))};if(specialty==='Vitreoretinal')obj.vr=obj.specialtyData;return obj}
$('caseForm').onsubmit=async e=>{e.preventDefault();$('privacyWarning').hidden=true;try{let input=caseFromForm();const prior=state.cases.find(c=>c.caseId===input.caseId);let transitionConfirmed=false;if(prior?.status==='IP_HOLD'&&input.status==='PUBLIC_READY'){transitionConfirmed=confirm('Этот случай имеет IP_HOLD. Подтвердить перевод в PUBLIC_READY?');if(!transitionConfirmed)return}if(prior&&!canTransitionStatus(prior.status,input.status,transitionConfirmed))throw new Error('Invalid status transition');input.revision=Number(prior?.revision||0)+1;const rec=validateCase(input);const idx=state.cases.findIndex(c=>c.caseId===rec.caseId);if(idx>=0)state.cases[idx]=rec;else state.cases.push(rec);queue('case',rec.caseId,rec,Number(prior?.revision||0),'UPSERT',transitionConfirmed);await persist();$('saveMessage').textContent='Сохранено локально ✓';setTimeout(()=>$('saveMessage').textContent='',1800);resetCaseForm();refreshAll();}catch(err){if(err.findings){$('privacyWarning').hidden=false;$('privacyWarning').innerHTML=`<b>Возможные идентификаторы пациента:</b> ${err.findings.map(x=>esc(x.match)).join(', ')}. Удали их из записи.`}else alert(err.message)}};
function resetCaseForm(){$('caseForm').reset();currentEdit=null;renderSpecialty('');initDefaults();}
$('resetCase').onclick=resetCaseForm;
$('caseId').oninput=()=>{if(!$('mediaStorageId').value||$('mediaStorageId').value.startsWith('MS-'))$('mediaStorageId').value=$('caseId').value};
function renderFollowSelect(){$('fuCaseId').innerHTML=state.cases.filter(c=>!c.archived).sort((a,b)=>b.surgeryDate.localeCompare(a.surgeryDate)).map(c=>`<option value="${esc(c.caseId)}">${esc(c.caseId)} · ${esc(c.procedure)}</option>`).join('')||'<option value="">Нет операций</option>'}
$('followForm').onsubmit=async e=>{e.preventDefault();const caseId=$('fuCaseId').value;if(!caseId)return;const existing=state.followups.filter(f=>f.caseId===caseId);const rec={followupId:crypto.randomUUID(),caseId,point:$('fuPoint').value,date:$('fuDate').value,bcva:$('fuBcva').value,iop:$('fuIop').value?Number($('fuIop').value):null,medications:$('fuMeds').value?Number($('fuMeds').value):null,refraction:$('fuRefraction').value,graftStatus:$('fuGraft').value,iolStatus:$('fuIol').value,retinalAttachment:$('fuRetina').value,complication:$('fuComp').value,reintervention:$('fuReint').value,outcome:$('fuOutcome').value.trim(),nextReview:$('fuNext').value,revision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.followups.push(rec);queue('followup',rec.followupId,rec,0);await persist();$('followForm').reset();$('fuDate').value=today();renderFollowSelect();$('fuMessage').textContent='Follow-up сохранён ✓';setTimeout(()=>$('fuMessage').textContent='',1800);refreshAll()};
